info:
  title: Project REST API

tags:
  - name: list
    description: Projects and associated metadata

paths:
  /project/list_all:
    get:
      tags:
        - list
      summary: Get projects
      description: >-
        Retrieve metadata for all projects.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /project/list_mine:
    get:
      tags:
        - list
      summary: Get projects per user
      description: >-
        Retrieve metadata for projects submitted per user.
      security:
        - BearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        "401":
          description: >-
            Unauthorized (expired token, missing header)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "422":
          description: >-
            Unprocessable Content (not enough segments, signature verification failed)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Missing authorization header
  schemas:
    Project:
      type: array
      items:
        type: object
        properties:
          contact_institution:
            type: string
            description: >-
              The institution or affiliation of `contact_name`
          contact_name:
            type: string
            description: >-
              The author of the data or a contact person responsible for adding the data
          date_added:
            type: integer
            description: >-
              POSIX timestamp corresponding to the date the project was added. In
              Sci-ModoM (UI), this is converted to YYYY-MM-DD (ISO 8601).
          date_published:
            type: integer
            description: >-
              POSIX timestamp corresponding to the date of publication. In
              Sci-ModoM (UI), this is converted to YYYY-MM-DD (ISO 8601).
          doi:
            type: string
            description: A list of DOIs associated with this project
          pmid:
            type: string
            description: A list of PMIDs associated with this project
          project_id:
            type: string
            description: Project identifier (SMID)
          project_summary:
            type: string
            description: Project summary
          project_title:
            type: string
            description: Project title
