"""Sci-Modom specifications and other constants/parameters
"""

# ID length
SMID_LENGTH = 8
EUFID_LENGTH = 12
ASSEMBLY_NUM_LENGTH = 12

# EUF
# cf. DatasetService, Exporter
SPECS_EUF = {
    "versions": ["1.6", "1.7", "1.8"],
    "1.6": {
        "headers": {
            "fileformat": "file_format",
            "organism": "taxa_id",
            "modification_type": "modification_type",
            "assembly": "assembly_name",
            "annotation_source": "annotation_source",
            "annotation_version": "annotation_version",
            "sequencing_platform": "sequencing_platform",
            "basecalling": "basecalling",
            "bioinformatics_workflow": "bioinformatics_workflow",
            "experiment": "experiment",
            "external_source": "external_source",
        },
        "required": [
            "fileformat",
            "organism",
            "modification_type",
            "assembly",
            "annotation_source",
            "annotation_version",
        ],
        "columns": {
            "chrom": "chrom",
            "chromStart": "start",
            "chromEnd": "end",
            "name": "name",
            "score": "score",
            "strand": "strand",
            "thickStart": "thick_start",
            "thickEnd": "thick_end",
            "itemRgb": "item_rgb",
            "coverage": "coverage",
            "frequency": "frequency",
            "refBase": "ref_base",
        },
    },
    "1.7": {
        "headers": {
            "fileformat": "file_format",
            "organism": "taxa_id",
            "modification_type": "modification_type",
            "assembly": "assembly_name",
            "annotation_source": "annotation_source",
            "annotation_version": "annotation_version",
            "sequencing_platform": "sequencing_platform",
            "basecalling": "basecalling",
            "bioinformatics_workflow": "bioinformatics_workflow",
            "experiment": "experiment",
            "external_source": "external_source",
        },
        "required": [
            "fileformat",
            "organism",
            "modification_type",
            "assembly",
            "annotation_source",
            "annotation_version",
        ],
    },
    "1.8": {
        "headers": {
            "fileformat": "file_format",
            "organism": "taxa_id",
            "modification_type": "modification_type",
            "assembly": "assembly_name",
            "annotation_source": "annotation_source",
            "annotation_version": "annotation_version",
            "sequencing_platform": "sequencing_platform",
            "basecalling": "basecalling",
            "bioinformatics_workflow": "bioinformatics_workflow",
            "experiment": "experiment",
            "external_source": "external_source",
        },
        "required": [
            "fileformat",
            "organism",
            "modification_type",
            "assembly",
            "annotation_source",
            "annotation_version",
        ],
    },
}

# Assembly/Annotation
ENSEMBL_FTP = "https://ftp.ensembl.org/pub"
# release 110
ENSEMBL_SERVER = "http://jul2023.rest.ensembl.org"  # "http://rest.ensembl.org"
ENSEMBL_DATA = "info/data"
ENSEMBL_ASM = "info/assembly"
ENSEMBL_ASM_MAPPING = "release-110/assembly_chain"  # "current_assembly_chain"

# GtRNAdb annotation
GTRNADB_URL = "http://gtrnadb.ucsc.edu/genomes/"

# Only GTF annotation: defined in AnnotationService

BIOTYPES = {
    "IG_C_gene": "Ig coding",
    "IG_D_gene": "Ig coding",
    "IG_J_gene": "Ig coding",
    "IG_J_pseudogene": "Pseudogene",
    "IG_V_gene": "Ig coding",
    "IG_V_pseudogene": "Pseudogene",
    "IG_gene": "Ig coding",
    "IG_pseudogene": "Pseudogene",
    "LRG_gene": "LRG",
    "Mt_rRNA": "ncRNA",
    "Mt_tRNA": "ncRNA",
    "Mt_tRNA_pseudogene": "Pseudogene",
    "RNA-Seq_gene": "Undefined",
    "TEC": "TEC",
    "TR_gene": "TcR coding",
    "TR_pseudogene": "Pseudogene",
    "ambiguous_orf": "lncRNA",
    "cdna_update": "Undefined",
    "cDNA": "Undefined",
    "disrupted_domain": "Pseudogene",
    "EST": "Undefined",
    "lincRNA": "lncRNA",
    "miRNA": "ncRNA",
    "miRNA_pseudogene": "Pseudogene",
    "misc_RNA": "ncRNA",
    "misc_RNA_pseudogene": "Pseudogene",
    "ncRNA": "ncRNA",
    "non_coding": "lncRNA",
    "nonsense_mediated_decay": "NMD coding",
    "polymorphic_pseudogene": "Pseudogene",
    "processed_pseudogene": "Pseudogene",
    "processed_transcript": "lncRNA",
    "protein_coding": "Protein coding",
    "pseudogene": "Pseudogene",
    "rRNA": "ncRNA",
    "rRNA_pseudogene": "Pseudogene",
    "retained_intron": "lncRNA",
    "scRNA_pseudogene": "Pseudogene",
    "snRNA": "ncRNA",
    "snRNA_pseudogene": "Pseudogene",
    "snlRNA": "ncRNA",
    "snoRNA": "ncRNA",
    "snoRNA_pseudogene": "Pseudogene",
    "tRNA": "ncRNA",
    "tRNA_pseudogene": "Pseudogene",
    "transcribed_processed_pseudogene": "Pseudogene",
    "transcribed_unprocessed_pseudogene": "Pseudogene",
    "unitary_pseudogene": "Pseudogene",
    "unprocessed_pseudogene": "Pseudogene",
    "ncRNA_host": "lncRNA",
    "TR_V_pseudogene": "Pseudogene",
    "TR_V_gene": "TcR coding",
    "IG_C_pseudogene": "Pseudogene",
    "TR_C_gene": "TcR coding",
    "TR_J_gene": "TcR coding",
    "protein_coding_in_progress": "Undefined",
    "IG_M_gene": "Ig coding",
    "IG_Z_gene": "Ig coding",
    "3prime_overlapping_ncRNA": "lncRNA",
    "antisense_RNA": "lncRNA",
    "scRNA": "ncRNA",
    "RNase_MRP_RNA": "ncRNA",
    "RNase_P_RNA": "ncRNA",
    "telomerase_RNA": "ncRNA",
    "sense_intronic": "lncRNA",
    "sense_overlapping": "lncRNA",
    "TR_D_gene": "TcR coding",
    "TR_J_pseudogene": "Pseudogene",
    "ncbi_pseudogene": "Pseudogene",
    "non_stop_decay": "NSD coding",
    "pre_miRNA": "ncRNA",
    "tmRNA": "ncRNA",
    "SRP_RNA": "ncRNA",
    "ribozyme": "lncRNA",
    "ncRNA_pseudogene": "Pseudogene",
    "IG_LV_gene": "Ig coding",
    "translated_processed_pseudogene": "Pseudogene",
    "nontranslating_CDS": "Other coding",
    "translated_unprocessed_pseudogene": "Pseudogene",
    "mRNA": "Protein coding",
    "artifact": "Undefined",
    "class_I_RNA": "ncRNA",
    "class_II_RNA": "ncRNA",
    "known_ncRNA": "ncRNA",
    "transcribed_unitary_pseudogene": "Pseudogene",
    "piRNA": "ncRNA",
    "scaRNA": "ncRNA",
    "sRNA": "ncRNA",
    "antitoxin": "lncRNA",
    "macro_lncRNA": "lncRNA",
    "IG_D_pseudogene": "Pseudogene",
    "guide_RNA": "ncRNA",
    "Y_RNA": "ncRNA",
    "transposable_element": "Undefined",
    "bidirectional_promoter_lncRNA": "lncRNA",
    "unknown_likely_coding": "Other coding",
    "lncRNA": "lncRNA",
    "aligned_transcript": "Undefined",
    "antisense": "lncRNA",
    "vault_RNA": "ncRNA",
    "rnaseq_putative_cds": "Other coding",
    "transcribed_pseudogene": "Pseudogene",
    "other": "Undefined",
    "pseudogene_with_CDS": "Pseudogene",
    "misc_non_coding": "ncRNA",
    "miRNA_primary_transcript": "ncRNA",
    "protein_coding_CDS_not_defined": "lncRNA",
    "protein_coding_LoF": "LoF coding",
}
