import json
from os.path import exists, join
from urllib.parse import quote
from flask import Blueprint, redirect

from scimodom.config import get_config
from scimodom.services.url import (
    CONFIRM_USER_REGISTRATION_URI,
    REQUEST_PASSWORD_RESET_URI,
    API_PREFIX,
)
from scimodom.services.user import get_user_service, WrongUserOrPassword

frontend = Blueprint("frontend", __name__, static_folder=get_config().FRONTEND_PATH)


@frontend.route(f"/{CONFIRM_USER_REGISTRATION_URI}/<email>/<token>")
def confirm_user_registration(email: str, token: str):
    """Activate a registered user.

    Validate the confirmation token (email link
    created by POST /users), and redirect.
    Set-Cookie header used by the FE Dialog box.

    :param email: The email inserted in the
    confirmation link
    :param token: The token inserted in the
    confirmation link.
    :statuscode 302: Redirect
    :statuscode 500: Internal Server Error
    """
    response = redirect("/")
    user_service = get_user_service()
    workflow_status = {
        "operation": "user_registration",
        "email": email,
    }
    try:
        user_service.confirm_user(email, token)
        workflow_status["result"] = "success"
    except WrongUserOrPassword:
        workflow_status["result"] = "failure"
    response.set_cookie("workflow_status", quote(json.dumps(workflow_status)))
    return response


@frontend.route(f"/{REQUEST_PASSWORD_RESET_URI}/<email>/<token>")
def request_password_reset(email: str, token: str):
    """Request a reset token.

    Set-Cookie header used by the FE Dialog box
    and redirect (email link created by /users/password/request).

    :param email: The email inserted in the
    confirmation link
    :param token: The token inserted in the
    confirmation link.
    :statuscode 302: Redirect
    :statuscode 500: Internal Server Error
    """
    response = redirect("/")
    workflow_status = {"operation": "password_reset", "email": email, "token": token}
    response.set_cookie("workflow_status", quote(json.dumps(workflow_status)))
    return response


@frontend.route("/", defaults={"path": "index.html"})
@frontend.route("/<path:path>")
def index(path: str):
    """Serve static route.

    NOTE: Serve the files generated by Vue
    as static content (production only).

    :param path: Route
    :statuscode 404: Not Found
    :statuscode 500: Internal Server Error
    """
    if path.startswith(API_PREFIX):
        return {"message": "API endpoint not found"}, 404
    if exists(join(get_config().FRONTEND_PATH, path)):
        return frontend.send_static_file(path)
    else:
        return frontend.send_static_file("index.html")
