name: Bug Report
description: Create a report to help us improve Sci-ModoM
title: ""
labels: "T: type:bug"
assignees:
  - eboileau
body:
  - type: textarea
    id: what-happened
    attributes:
      label: A clear and concise description of what the bug is.
      description: Describe the expected behavior and the issue you're experiencing. Make sure that this bug has not already been filed before
opening a duplicate issue.
      value: |
        Minimal steps to reproduce the bug:
        1. step 1
        2. step 2
        3. you get it...
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Output or error messages.
      description: If relevant, paste the output of the steps above, commands, traceback, etc. or drag images or log files in.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here. 
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browser were you using?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: What version of Sci-ModoM were you using?
      multiple: true
      options:
        - v0.0.2
        - master
        - dev
    validations:
      required: true
