name: Feature Request
description: Suggest an idea to improve Sci-ModoM
title: ""
labels: "T: type:enhancement"
assignees:
  - eboileau
body:
  - type: checkboxes
    attributes:
      label: Is this related to an existing bug, feature or PR request?
      description: If yes, please add a link to the issue/PR number in the next section.
      options:
      - label: Is this related to an existing issue or PR?
        required: true
  - type: textarea
    id: context
    attributes:
      label: Is your suggestion related to a problem to be solved?
      description: Provide a clear and concise description of what the problem is.
      value: |
        If this is related to an existing issue/PR, please link here.
    validations:
      required: false
  - type: textarea
    id: request
    attributes:
      label: A concise description of your feature request.
      description: Describe a possible solution. Did you consider alternative solutions? 
    validations:
      required: true
      
