version: "3"
services:
  scimodom_db:
    env_file: .env
    image: ${DB_IMAGE_NAME}
    volumes:
      - ${HOST_SECRETS_DIR}:/run/secrets
      - ${HOST_BACKUP_DIR}:/backup
      - ${HOST_DB_DATA_DIR}:/var/lib/mysql
    restart: always

  scimodom_app:
    env_file: .env
    image: ${APP_IMAGE_NAME}
    depends_on:
      - scimodom_db
    ports:
      - "${HTTP_PORT}:8000"
    volumes:
      - ${HOST_SECRETS_DIR}:/run/secrets
      - ${HOST_IMPORT_DIR}:/import
      - ${HOST_DATA_DIR}:/data
      - ${HOST_BACKUP_DIR}:/backup
      - ${HOST_CONFIG_DIR}/config.js:/frontend/config.js
    restart: always
