alabaster==0.7.13
alembic==1.12.0
Babel==2.12.1
blinker==1.6.2
certifi==2023.7.22
cfgv==3.4.0
charset-normalizer==3.2.0
click==8.1.6
distlib==0.3.7
docutils==0.20.1
exceptiongroup==1.1.3
filelock==3.12.4
Flask==2.3.2
Flask-Cors==4.0.0
greenlet==2.0.2
identify==2.5.28
idna==3.4
imagesize==1.4.1
importlib-metadata==6.8.0
iniconfig==2.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
Mako==1.2.4
MarkupSafe==2.1.3
mysqlclient==2.2.0
nodeenv==1.8.0
numpy==1.25.2
packaging==23.1
pandas==2.0.3
pkg_resources==0.0.0
platformdirs==3.10.0
pluggy==1.2.0
pre-commit==3.4.0
Pygments==2.16.1
pytest==7.4.0
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
-e git+https://github.com/dieterich-lab/scimodom.git@afa9f584c6a250eb6e10ec4f50a75f445a1ae089#egg=scimodom&subdirectory=server
shortuuid==1.0.11
six==1.16.0
snowballstemmer==2.2.0
Sphinx==7.2.6
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
SQLAlchemy==2.0.19
tomli==2.0.1
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.5
virtualenv==20.24.5
Werkzeug==2.3.6
zipp==3.16.2
