"""add_rna_table

Revision ID: 04540395cc99
Revises: 2030d7195a9b
Create Date: 2024-04-30 09:53:51.810164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04540395cc99"
down_revision = "2030d7195a9b"
branch_labels = None
depends_on = None

# add table, upsert (fill table), then add constraints (see next upgrade)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rna_type",
        sa.Column("id", sa.String(length=32), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rna_type")),
        sa.UniqueConstraint("name", name=op.f("uq_rna_type_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rna_type")
    # ### end Alembic commands ###
