"""add_project_source

Revision ID: 5800126056c3
Revises: 46cf79e27b16
Create Date: 2023-08-10 11:47:56.778569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5800126056c3"
down_revision = "46cf79e27b16"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("pmid", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("project", "pmid")
    op.drop_column("project", "doi")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("doi", mysql.VARCHAR(length=255), nullable=True))
    op.add_column(
        "project",
        sa.Column(
            "pmid", mysql.INTEGER(display_width=11), autoincrement=False, nullable=True
        ),
    )
    op.drop_table("project_source")
    # ### end Alembic commands ###
