"""scimodom_schema_v2

Revision ID: 665ece797465
Revises: abbad4ef0a9c
Create Date: 2023-09-20 10:52:26.191121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "665ece797465"
down_revision = "abbad4ef0a9c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assembly_version",
        sa.Column("version_num", sa.String(length=12), nullable=False),
        sa.PrimaryKeyConstraint("version_num"),
    )
    op.add_column(
        "assembly", sa.Column("version", sa.String(length=12), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assembly", "version")
    op.drop_table("assembly_version")
    # ### end Alembic commands ###
