"""add_rna_constraints

Revision ID: 6e255bc2f48f
Revises: 04540395cc99
Create Date: 2024-04-30 11:00:18.177602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e255bc2f48f"
down_revision = "04540395cc99"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_modification_rna_rna_type"),
        "modification",
        "rna_type",
        ["rna"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_modification_rna_rna_type"), "modification", type_="foreignkey"
    )
    # ### end Alembic commands ###
