"""drop_annotation

Revision ID: 79fa0c30513f
Revises: 1c61e979733b
Create Date: 2023-12-14 14:30:30.442283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "79fa0c30513f"
down_revision = "1c61e979733b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dataset",
        "annotation_source",
        existing_type=mysql.VARCHAR(length=128),
        nullable=True,
    )
    op.alter_column(
        "dataset",
        "annotation_version",
        existing_type=mysql.VARCHAR(length=128),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dataset",
        "annotation_version",
        existing_type=mysql.VARCHAR(length=128),
        nullable=False,
    )
    op.alter_column(
        "dataset",
        "annotation_source",
        existing_type=mysql.VARCHAR(length=128),
        nullable=False,
    )
    # ### end Alembic commands ###
