"""add_idx_gene_name_lookup

Revision ID: a01504318ae7
Revises: 3af0dcd286cf
Create Date: 2026-10-06 10:54:24.240693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a01504318ae7"
down_revision = "3af0dcd286cf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_genomic_name",
        "genomic_annotation",
        ["annotation_id", "name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_genomic_name", table_name="genomic_annotation")
    # ### end Alembic commands ###
