"""fix_minor_v1

Revision ID: abbad4ef0a9c
Revises: 5800126056c3
Create Date: 2023-09-19 16:30:54.231393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "abbad4ef0a9c"
down_revision = "5800126056c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        constraint_name="project_source_ibfk_1",
        table_name="project_source",
        type_="foreignkey",
    )
    op.drop_constraint(
        constraint_name="dataset_ibfk_1", table_name="dataset", type_="foreignkey"
    )

    op.alter_column(
        "project",
        "id",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.String(length=8),
        existing_nullable=False,
    )
    op.alter_column(
        "project_source",
        "project_id",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.String(length=8),
        existing_nullable=False,
    )
    op.alter_column(
        "dataset",
        "project_id",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.String(length=8),
        existing_nullable=False,
    )

    op.create_foreign_key(
        constraint_name="project_source_ibfk_1",
        source_table="project_source",
        referent_table="project",
        local_cols=["project_id"],
        remote_cols=["id"],
    )
    op.create_foreign_key(
        constraint_name="dataset_ibfk_1",
        source_table="dataset",
        referent_table="project",
        local_cols=["project_id"],
        remote_cols=["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CHANGED: DROP CONSTRAINT, ALTER COLUMN, CREATE CONSTRAINT
    op.drop_constraint(
        constraint_name="project_source_ibfk_1",
        table_name="project_source",
        type_="foreignkey",
    )
    op.drop_constraint(
        constraint_name="dataset_ibfk_1", table_name="dataset", type_="foreignkey"
    )

    op.alter_column(
        "project",
        "id",
        existing_type=sa.String(length=8),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=False,
    )
    op.alter_column(
        "project_source",
        "project_id",
        existing_type=sa.String(length=8),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=False,
    )
    op.alter_column(
        "dataset",
        "project_id",
        existing_type=sa.String(length=8),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=False,
    )

    op.create_foreign_key(
        constraint_name="project_source_ibfk_1",
        source_table="project_source",
        referent_table="project",
        local_cols=["project_id"],
        remote_cols=["id"],
    )
    op.create_foreign_key(
        constraint_name="dataset_ibfk_1",
        source_table="dataset",
        referent_table="project",
        local_cols=["project_id"],
        remote_cols=["id"],
    )
    # ### end Alembic commands ###
