"""assembly_drop_constraint

Revision ID: be4f58630610
Revises: 80658585dbb2
Create Date: 2024-06-11 17:16:15.019905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "be4f58630610"
down_revision = "80658585dbb2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assembly", "alt_name", existing_type=mysql.VARCHAR(length=128), nullable=True
    )
    op.drop_index("uq_assembly_alt_name", table_name="assembly")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("uq_assembly_alt_name", "assembly", ["alt_name"], unique=True)
    op.alter_column(
        "assembly", "alt_name", existing_type=mysql.VARCHAR(length=128), nullable=False
    )
    # ### end Alembic commands ###
