"""scimodom_schema_v3

Revision ID: be9340f7ff6e
Revises: 665ece797465
Create Date: 2023-09-20 12:33:22.376640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "be9340f7ff6e"
down_revision = "665ece797465"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_name", sa.String(length=128), nullable=False),
        sa.Column("contact_institution", sa.String(length=255), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("project", sa.Column("contact_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "project", "project_contact", ["contact_id"], ["id"])
    op.drop_column("project", "contact_email")
    op.drop_column("project", "contact_name")
    op.drop_column("project", "contact_institution")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("contact_institution", mysql.VARCHAR(length=255), nullable=False),
    )
    op.add_column(
        "project", sa.Column("contact_name", mysql.VARCHAR(length=128), nullable=False)
    )
    op.add_column(
        "project", sa.Column("contact_email", mysql.VARCHAR(length=320), nullable=False)
    )
    op.drop_constraint(None, "project", type_="foreignkey")
    op.drop_column("project", "contact_id")
    op.drop_table("project_contact")
    # ### end Alembic commands ###
