"""add_uc_rm_tbl

Revision ID: c3c761aca33b
Revises: 220c23fda34a
Create Date: 2025-04-16 16:13:42.660128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c3c761aca33b"
down_revision = "220c23fda34a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_sprinzl_data_id', table_name='sprinzl')
    op.drop_constraint(
        "fk_sprinzl_data_id_data", table_name="sprinzl", type_="foreignkey"
    )
    op.drop_index("uq_sprinzl_data_id", table_name="sprinzl")
    op.drop_table("sprinzl")
    op.alter_column(
        "modomics",
        "reference_id",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_modomics_reference_id"), "modomics", ["reference_id"]
    )
    op.create_unique_constraint(
        op.f("uq_user_project_association_user_id"),
        "user_project_association",
        ["user_id", "project_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_user_project_association_user_id"),
        "user_project_association",
        type_="unique",
    )
    op.drop_constraint(op.f("uq_modomics_reference_id"), "modomics", type_="unique")
    op.alter_column(
        "modomics",
        "reference_id",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=True,
    )
    op.create_table(
        "sprinzl",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "data_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("position", mysql.VARCHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_id"], ["data.id"], name="fk_sprinzl_data_id_data"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "uq_sprinzl_data_id", "sprinzl", ["data_id", "position"], unique=True
    )
    # op.create_index('ix_sprinzl_data_id', 'sprinzl', ['data_id'], unique=False)
    # ### end Alembic commands ###
