"""modomics

Revision ID: cee4ad23a519
Revises: 6faa5954d595
Create Date: 2026-05-15 21:55:42.546498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cee4ad23a519"
down_revision = "6faa5954d595"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modomics",
        sa.Column("reference_nucleobase", sa.String(length=32), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modomics", "reference_nucleobase")
    # ### end Alembic commands ###
